# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PDjC1a7l-AvQYzLhZ3nF1XWExQyXGERk
"""

import streamlit as st
from joblib import load
import numpy as np
import pandas as pd

# 加载模型
model = load('random_forest_model.joblib')  # 确保模型文件名正确

# 应用标题
st.title("Anemia detection model deployment")
st.write("Anemia was determined by entering gender and RGB values")

# 侧边栏输入
st.sidebar.header("input data")

# 添加性别选择
sex = st.sidebar.selectbox(
    "Gender",
    options=['Male', 'Female']
)

# RGB 数值输入
red_pixel = st.sidebar.slider("%Red Pixel", min_value=0.0, max_value=100.0, value=50.0, step=0.1)
green_pixel = st.sidebar.slider("%Green pixel", min_value=0.0, max_value=100.0, value=50.0, step=0.1)
blue_pixel = st.sidebar.slider("%Blue pixel", min_value=0.0, max_value=100.0, value=50.0, step=0.1)

# 显示用户输入
st.write("The data you entered is as follows：")
st.write(f"Gender: {sex}")
st.write(f"%Red Pixel: {red_pixel}%")
st.write(f"%Green pixel: {green_pixel}%")
st.write(f"%Blue pixel: {blue_pixel}%")

# 预测按钮
if st.button("Predict whether or not you are anemic"):
    try:
        # 创建输入数据框，确保特征顺序与训练时一致
        input_data = pd.DataFrame({
            'Sex': [sex],
            '%Red Pixel': [red_pixel],
            '%Green pixel': [green_pixel],
            '%Blue pixel': [blue_pixel]
        })

        # 使用模型预测
        prediction = model.predict(input_data)
        prediction_proba = model.predict_proba(input_data)

        # 显示预测结果
        st.subheader("predict")
        if prediction[0] == "Yes":
            st.write("Results: anemia")
        else:
            st.write("Results: no anemia")

        # 显示置信概率
        st.write("Model confidence probability：")
        st.write(f"No：{prediction_proba[0][0]:.2f}")
        st.write(f"Yes：{prediction_proba[0][1]:.2f}")

    except Exception as e:
        st.error(f"An error occurred in the prediction process：{str(e)}")